use super::books::BookInfo;

/// Afrikaans 1933/1953 book names and common STT variants.
pub const AF_BOOKS: &[BookInfo] = &[
    BookInfo {
        number: 1,
        name: "Genesis",
        abbreviation: "Gen",
        aliases: &["genesis"],
    },
    BookInfo {
        number: 2,
        name: "Eksodus",
        abbreviation: "Eks",
        aliases: &["eksodus", "exodus"],
    },
    BookInfo {
        number: 3,
        name: "Levitikus",
        abbreviation: "Lev",
        aliases: &["levitikus", "leviticus"],
    },
    BookInfo {
        number: 4,
        name: "Numeri",
        abbreviation: "Num",
        aliases: &["numeri", "numbers"],
    },
    BookInfo {
        number: 5,
        name: "Deuteronomium",
        abbreviation: "Deut",
        aliases: &["deuteronomium", "deuteronomy"],
    },
    BookInfo {
        number: 6,
        name: "Josua",
        abbreviation: "Jos",
        aliases: &["josua", "joshua"],
    },
    BookInfo {
        number: 7,
        name: "Rigters",
        abbreviation: "Rig",
        aliases: &["rigters", "judges"],
    },
    BookInfo {
        number: 8,
        name: "Rut",
        abbreviation: "Rut",
        aliases: &["ruth"],
    },
    BookInfo {
        number: 9,
        name: "1 Samuel",
        abbreviation: "1 Sam",
        aliases: &[
            "1 samuel",
            "eerste samuel",
            "1ste samuel",
            "1 sam",
            "1sam",
        ],
    },
    BookInfo {
        number: 10,
        name: "2 Samuel",
        abbreviation: "2 Sam",
        aliases: &[
            "2 samuel",
            "tweede samuel",
            "2de samuel",
            "2 sam",
            "2sam",
        ],
    },
    BookInfo {
        number: 11,
        name: "1 Konings",
        abbreviation: "1 Kon",
        aliases: &[
            "1 konings",
            "eerste konings",
            "1ste konings",
            "1 kon",
            "1kon",
        ],
    },
    BookInfo {
        number: 12,
        name: "2 Konings",
        abbreviation: "2 Kon",
        aliases: &[
            "2 konings",
            "tweede konings",
            "2de konings",
            "2 kon",
            "2kon",
        ],
    },
    BookInfo {
        number: 13,
        name: "1 Kronieke",
        abbreviation: "1 Kro",
        aliases: &[
            "1 kronieke",
            "eerste kronieke",
            "1ste kronieke",
            "1 kro",
            "1kro",
        ],
    },
    BookInfo {
        number: 14,
        name: "2 Kronieke",
        abbreviation: "2 Kro",
        aliases: &[
            "2 kronieke",
            "tweede kronieke",
            "2de kronieke",
            "2 kro",
            "2kro",
        ],
    },
    BookInfo {
        number: 15,
        name: "Esra",
        abbreviation: "Esra",
        aliases: &["ezra"],
    },
    BookInfo {
        number: 16,
        name: "Nehemia",
        abbreviation: "Neh",
        aliases: &["nehemiah"],
    },
    BookInfo {
        number: 17,
        name: "Ester",
        abbreviation: "Est",
        aliases: &["esther"],
    },
    BookInfo {
        number: 18,
        name: "Job",
        abbreviation: "Job",
        aliases: &[],
    },
    BookInfo {
        number: 19,
        name: "Psalms",
        abbreviation: "Ps",
        aliases: &["psalm", "psalms", "psalm van david"],
    },
    BookInfo {
        number: 20,
        name: "Spreuke van Salomo",
        abbreviation: "Spr",
        aliases: &["spreuke", "spreuke van salomo", "proverbs"],
    },
    BookInfo {
        number: 21,
        name: "Prediker",
        abbreviation: "Pred",
        aliases: &["prediker", "ecclesiastes"],
    },
    BookInfo {
        number: 22,
        name: "Hooglied van Salomo",
        abbreviation: "Hoog",
        aliases: &["hooglied", "song of solomon"],
    },
    BookInfo {
        number: 23,
        name: "Jesaja",
        abbreviation: "Jes",
        aliases: &["jesaja", "isaiah", "esaias"],
    },
    BookInfo {
        number: 24,
        name: "Jeremia",
        abbreviation: "Jer",
        aliases: &["jeremiah"],
    },
    BookInfo {
        number: 25,
        name: "Klaagliedere van Jeremia",
        abbreviation: "Klaag",
        aliases: &["klaagliedere", "lamentations"],
    },
    BookInfo {
        number: 26,
        name: "Esegiël",
        abbreviation: "Eseg",
        aliases: &["esegiel", "ezekiel"],
    },
    BookInfo {
        number: 27,
        name: "Daniël",
        abbreviation: "Dan",
        aliases: &["daniel"],
    },
    BookInfo {
        number: 28,
        name: "Hosea",
        abbreviation: "Hos",
        aliases: &[],
    },
    BookInfo {
        number: 29,
        name: "Joël",
        abbreviation: "Joel",
        aliases: &["joel"],
    },
    BookInfo {
        number: 30,
        name: "Amos",
        abbreviation: "Amos",
        aliases: &[],
    },
    BookInfo {
        number: 31,
        name: "Obadja",
        abbreviation: "Obad",
        aliases: &["obadiah"],
    },
    BookInfo {
        number: 32,
        name: "Jona",
        abbreviation: "Jona",
        aliases: &["jonah"],
    },
    BookInfo {
        number: 33,
        name: "Miga",
        abbreviation: "Mig",
        aliases: &["miga", "micah"],
    },
    BookInfo {
        number: 34,
        name: "Nahum",
        abbreviation: "Nah",
        aliases: &[],
    },
    BookInfo {
        number: 35,
        name: "Habakuk",
        abbreviation: "Hab",
        aliases: &["habakkuk"],
    },
    BookInfo {
        number: 36,
        name: "Sefanja",
        abbreviation: "Sef",
        aliases: &["sefanja", "zephaniah"],
    },
    BookInfo {
        number: 37,
        name: "Haggai",
        abbreviation: "Hag",
        aliases: &["haggai"],
    },
    BookInfo {
        number: 38,
        name: "Sagaria",
        abbreviation: "Sag",
        aliases: &["sagaria", "zechariah"],
    },
    BookInfo {
        number: 39,
        name: "Maleagi",
        abbreviation: "Mal",
        aliases: &["maleagi", "malachi"],
    },
    BookInfo {
        number: 40,
        name: "Matteus",
        abbreviation: "Matt",
        aliases: &["matteus", "matthew"],
    },
    BookInfo {
        number: 41,
        name: "Markus",
        abbreviation: "Mark",
        aliases: &["markus", "mark"],
    },
    BookInfo {
        number: 42,
        name: "Lukas",
        abbreviation: "Luk",
        aliases: &["lukas", "luke"],
    },
    BookInfo {
        number: 43,
        name: "Johannes",
        abbreviation: "Joh",
        aliases: &["johannes", "john"],
    },
    BookInfo {
        number: 44,
        name: "Die handelinge van die apostels",
        abbreviation: "Hand",
        aliases: &[
            "handelinge",
            "die handelinge",
            "handelinge van die apostels",
            "acts",
        ],
    },
    BookInfo {
        number: 45,
        name: "Romeine",
        abbreviation: "Rom",
        aliases: &["romeine", "romans"],
    },
    BookInfo {
        number: 46,
        name: "1 Korintiërs",
        abbreviation: "1 Kor",
        aliases: &[
            "1 korintiers",
            "1 kor",
            "1kor",
            "eerste korintiers",
            "1 corinthians",
        ],
    },
    BookInfo {
        number: 47,
        name: "2 Korintiërs",
        abbreviation: "2 Kor",
        aliases: &[
            "2 korintiers",
            "2 kor",
            "2kor",
            "tweede korintiers",
            "2 corinthians",
        ],
    },
    BookInfo {
        number: 48,
        name: "Galasiërs",
        abbreviation: "Gal",
        aliases: &["galasiers", "galatians"],
    },
    BookInfo {
        number: 49,
        name: "Effesiërs",
        abbreviation: "Ef",
        aliases: &["effesiers", "ephesians"],
    },
    BookInfo {
        number: 50,
        name: "Filippense",
        abbreviation: "Fil",
        aliases: &["filippense", "philippians"],
    },
    BookInfo {
        number: 51,
        name: "Kolossense",
        abbreviation: "Kol",
        aliases: &["kolossense", "colossians"],
    },
    BookInfo {
        number: 52,
        name: "1 Tessalonisense",
        abbreviation: "1 Tess",
        aliases: &[
            "1 tessalonisense",
            "1 tess",
            "1tess",
            "1 thessalonians",
        ],
    },
    BookInfo {
        number: 53,
        name: "2 Tessalonisense",
        abbreviation: "2 Tess",
        aliases: &[
            "2 tessalonisense",
            "2 tess",
            "2tess",
            "2 thessalonians",
        ],
    },
    BookInfo {
        number: 54,
        name: "1 Timoteus",
        abbreviation: "1 Tim",
        aliases: &["1 timoteus", "1 tim", "1tim", "1 timothy"],
    },
    BookInfo {
        number: 55,
        name: "2 Timoteus",
        abbreviation: "2 Tim",
        aliases: &["2 timoteus", "2 tim", "2tim", "2 timothy"],
    },
    BookInfo {
        number: 56,
        name: "Titus",
        abbreviation: "Tit",
        aliases: &[],
    },
    BookInfo {
        number: 57,
        name: "Filemon",
        abbreviation: "Filem",
        aliases: &["filemon", "philemon"],
    },
    BookInfo {
        number: 58,
        name: "Hebreërs",
        abbreviation: "Heb",
        aliases: &["hebreers", "hebrews"],
    },
    BookInfo {
        number: 59,
        name: "Jakobus",
        abbreviation: "Jak",
        aliases: &["jakobus", "james"],
    },
    BookInfo {
        number: 60,
        name: "1 Petrus",
        abbreviation: "1 Pet",
        aliases: &["1 petrus", "1 pet", "1pet", "1 peter"],
    },
    BookInfo {
        number: 61,
        name: "2 Petrus",
        abbreviation: "2 Pet",
        aliases: &["2 petrus", "2 pet", "2pet", "2 peter"],
    },
    BookInfo {
        number: 62,
        name: "1 Johannes",
        abbreviation: "1 Joh",
        aliases: &["1 johannes", "1 joh", "1joh", "1 john"],
    },
    BookInfo {
        number: 63,
        name: "2 Johannes",
        abbreviation: "2 Joh",
        aliases: &["2 johannes", "2 joh", "2joh", "2 john"],
    },
    BookInfo {
        number: 64,
        name: "3 Johannes",
        abbreviation: "3 Joh",
        aliases: &["3 johannes", "3 joh", "3joh", "3 john"],
    },
    BookInfo {
        number: 65,
        name: "Judas",
        abbreviation: "Jud",
        aliases: &["jude"],
    },
    BookInfo {
        number: 66,
        name: "Die openbaring",
        abbreviation: "Openb",
        aliases: &[
            "openbaring",
            "die openbaring",
            "revelation",
            "apocalypse",
        ],
    },
];
