use super::books::BookInfo;

pub const ES_BOOKS: &[BookInfo] = &[
    BookInfo { number: 1, name: "Genesis", abbreviation: "Gen", aliases: &["genesis", "génesis"] },
    BookInfo { number: 2, name: "Exodo", abbreviation: "Ex", aliases: &["exodo", "éxodo"] },
    BookInfo { number: 3, name: "Levitico", abbreviation: "Lev", aliases: &["levitico", "levítico"] },
    BookInfo { number: 4, name: "Numeros", abbreviation: "Num", aliases: &["numeros", "números"] },
    BookInfo { number: 5, name: "Deuteronomio", abbreviation: "Deut", aliases: &["deuteronomio"] },
    BookInfo { number: 6, name: "Josue", abbreviation: "Jos", aliases: &["josue", "josué"] },
    BookInfo { number: 7, name: "Jueces", abbreviation: "Jue", aliases: &["jueces"] },
    BookInfo { number: 8, name: "Rut", abbreviation: "Rut", aliases: &["rut", "ruth"] },
    BookInfo { number: 9, name: "1 Samuel", abbreviation: "1 Sam", aliases: &["1 samuel", "primero samuel", "primer samuel"] },
    BookInfo { number: 10, name: "2 Samuel", abbreviation: "2 Sam", aliases: &["2 samuel", "segundo samuel"] },
    BookInfo { number: 11, name: "1 Reyes", abbreviation: "1 Rey", aliases: &["1 reyes", "primero reyes", "primer reyes"] },
    BookInfo { number: 12, name: "2 Reyes", abbreviation: "2 Rey", aliases: &["2 reyes", "segundo reyes"] },
    BookInfo { number: 13, name: "1 Cronicas", abbreviation: "1 Cro", aliases: &["1 cronicas", "1 crónicas", "primero cronicas", "primer crónicas"] },
    BookInfo { number: 14, name: "2 Cronicas", abbreviation: "2 Cro", aliases: &["2 cronicas", "2 crónicas", "segundo cronicas", "segundo crónicas"] },
    BookInfo { number: 15, name: "Esdras", abbreviation: "Esd", aliases: &["esdras"] },
    BookInfo { number: 16, name: "Nehemias", abbreviation: "Neh", aliases: &["nehemias", "nehemías"] },
    BookInfo { number: 17, name: "Ester", abbreviation: "Est", aliases: &["ester"] },
    BookInfo { number: 18, name: "Job", abbreviation: "Job", aliases: &["job"] },
    BookInfo { number: 19, name: "Salmos", abbreviation: "Sal", aliases: &["salmos", "salmo"] },
    BookInfo { number: 20, name: "Proverbios", abbreviation: "Prov", aliases: &["proverbios"] },
    BookInfo { number: 21, name: "Eclesiastes", abbreviation: "Ecl", aliases: &["eclesiastes", "eclesiastés"] },
    BookInfo { number: 22, name: "Cantares", abbreviation: "Cant", aliases: &["cantares", "cantar de los cantares"] },
    BookInfo { number: 23, name: "Isaias", abbreviation: "Isa", aliases: &["isaias", "isaías"] },
    BookInfo { number: 24, name: "Jeremias", abbreviation: "Jer", aliases: &["jeremias", "jeremías"] },
    BookInfo { number: 25, name: "Lamentaciones", abbreviation: "Lam", aliases: &["lamentaciones"] },
    BookInfo { number: 26, name: "Ezequiel", abbreviation: "Eze", aliases: &["ezequiel"] },
    BookInfo { number: 27, name: "Daniel", abbreviation: "Dan", aliases: &["daniel"] },
    BookInfo { number: 28, name: "Oseas", abbreviation: "Os", aliases: &["oseas"] },
    BookInfo { number: 29, name: "Joel", abbreviation: "Joel", aliases: &["joel"] },
    BookInfo { number: 30, name: "Amos", abbreviation: "Am", aliases: &["amos", "amós"] },
    BookInfo { number: 31, name: "Abdias", abbreviation: "Abd", aliases: &["abdias", "abdías"] },
    BookInfo { number: 32, name: "Jonas", abbreviation: "Jon", aliases: &["jonas", "jonás"] },
    BookInfo { number: 33, name: "Miqueas", abbreviation: "Miq", aliases: &["miqueas"] },
    BookInfo { number: 34, name: "Nahum", abbreviation: "Nah", aliases: &["nahum", "nahúm"] },
    BookInfo { number: 35, name: "Habacuc", abbreviation: "Hab", aliases: &["habacuc"] },
    BookInfo { number: 36, name: "Sofonias", abbreviation: "Sof", aliases: &["sofonias", "sofonías"] },
    BookInfo { number: 37, name: "Hageo", abbreviation: "Hag", aliases: &["hageo"] },
    BookInfo { number: 38, name: "Zacarias", abbreviation: "Zac", aliases: &["zacarias", "zacarías"] },
    BookInfo { number: 39, name: "Malaquias", abbreviation: "Mal", aliases: &["malaquias", "malaquías"] },
    BookInfo { number: 40, name: "Mateo", abbreviation: "Mat", aliases: &["mateo"] },
    BookInfo { number: 41, name: "Marcos", abbreviation: "Mar", aliases: &["marcos"] },
    BookInfo { number: 42, name: "Lucas", abbreviation: "Luc", aliases: &["lucas"] },
    BookInfo { number: 43, name: "Juan", abbreviation: "Jn", aliases: &["juan"] },
    BookInfo { number: 44, name: "Hechos", abbreviation: "Hch", aliases: &["hechos", "hechos de los apostoles", "hechos de los apóstoles"] },
    BookInfo { number: 45, name: "Romanos", abbreviation: "Rom", aliases: &["romanos"] },
    BookInfo { number: 46, name: "1 Corintios", abbreviation: "1 Cor", aliases: &["1 corintios", "primero corintios", "primer corintios"] },
    BookInfo { number: 47, name: "2 Corintios", abbreviation: "2 Cor", aliases: &["2 corintios", "segundo corintios"] },
    BookInfo { number: 48, name: "Galatas", abbreviation: "Gal", aliases: &["galatas", "gálatas"] },
    BookInfo { number: 49, name: "Efesios", abbreviation: "Ef", aliases: &["efesios"] },
    BookInfo { number: 50, name: "Filipenses", abbreviation: "Fil", aliases: &["filipenses"] },
    BookInfo { number: 51, name: "Colosenses", abbreviation: "Col", aliases: &["colosenses"] },
    BookInfo { number: 52, name: "1 Tesalonicenses", abbreviation: "1 Tes", aliases: &["1 tesalonicenses", "primero tesalonicenses", "primer tesalonicenses"] },
    BookInfo { number: 53, name: "2 Tesalonicenses", abbreviation: "2 Tes", aliases: &["2 tesalonicenses", "segundo tesalonicenses"] },
    BookInfo { number: 54, name: "1 Timoteo", abbreviation: "1 Tim", aliases: &["1 timoteo", "primero timoteo", "primer timoteo"] },
    BookInfo { number: 55, name: "2 Timoteo", abbreviation: "2 Tim", aliases: &["2 timoteo", "segundo timoteo"] },
    BookInfo { number: 56, name: "Tito", abbreviation: "Tit", aliases: &["tito"] },
    BookInfo { number: 57, name: "Filemon", abbreviation: "Flm", aliases: &["filemon", "filemón"] },
    BookInfo { number: 58, name: "Hebreos", abbreviation: "Heb", aliases: &["hebreos"] },
    BookInfo { number: 59, name: "Santiago", abbreviation: "Stg", aliases: &["santiago"] },
    BookInfo { number: 60, name: "1 Pedro", abbreviation: "1 Ped", aliases: &["1 pedro", "primero pedro", "primer pedro"] },
    BookInfo { number: 61, name: "2 Pedro", abbreviation: "2 Ped", aliases: &["2 pedro", "segundo pedro"] },
    BookInfo { number: 62, name: "1 Juan", abbreviation: "1 Jn", aliases: &["1 juan", "primero juan", "primer juan"] },
    BookInfo { number: 63, name: "2 Juan", abbreviation: "2 Jn", aliases: &["2 juan", "segundo juan"] },
    BookInfo { number: 64, name: "3 Juan", abbreviation: "3 Jn", aliases: &["3 juan", "tercero juan", "tercer juan"] },
    BookInfo { number: 65, name: "Judas", abbreviation: "Jud", aliases: &["judas"] },
    BookInfo { number: 66, name: "Apocalipsis", abbreviation: "Apoc", aliases: &["apocalipsis"] },
];

pub const FR_BOOKS: &[BookInfo] = &[
    BookInfo { number: 1, name: "Genese", abbreviation: "Gen", aliases: &["genese", "genèse"] },
    BookInfo { number: 2, name: "Exode", abbreviation: "Ex", aliases: &["exode"] },
    BookInfo { number: 3, name: "Levitique", abbreviation: "Lev", aliases: &["levitique", "lévitique"] },
    BookInfo { number: 4, name: "Nombres", abbreviation: "Nom", aliases: &["nombres"] },
    BookInfo { number: 5, name: "Deuteronome", abbreviation: "Deut", aliases: &["deuteronome", "deutéronome"] },
    BookInfo { number: 6, name: "Josue", abbreviation: "Jos", aliases: &["josue", "josué"] },
    BookInfo { number: 7, name: "Juges", abbreviation: "Jug", aliases: &["juges"] },
    BookInfo { number: 8, name: "Ruth", abbreviation: "Ruth", aliases: &["ruth"] },
    BookInfo { number: 9, name: "1 Samuel", abbreviation: "1 Sam", aliases: &["1 samuel", "premier samuel"] },
    BookInfo { number: 10, name: "2 Samuel", abbreviation: "2 Sam", aliases: &["2 samuel", "deuxieme samuel", "deuxième samuel"] },
    BookInfo { number: 11, name: "1 Rois", abbreviation: "1 Rois", aliases: &["1 rois", "premier rois"] },
    BookInfo { number: 12, name: "2 Rois", abbreviation: "2 Rois", aliases: &["2 rois", "deuxieme rois", "deuxième rois"] },
    BookInfo { number: 13, name: "1 Chroniques", abbreviation: "1 Chr", aliases: &["1 chroniques", "premier chroniques"] },
    BookInfo { number: 14, name: "2 Chroniques", abbreviation: "2 Chr", aliases: &["2 chroniques", "deuxieme chroniques", "deuxième chroniques"] },
    BookInfo { number: 15, name: "Esdras", abbreviation: "Esd", aliases: &["esdras"] },
    BookInfo { number: 16, name: "Nehemie", abbreviation: "Neh", aliases: &["nehemie", "néhémie"] },
    BookInfo { number: 17, name: "Esther", abbreviation: "Est", aliases: &["esther"] },
    BookInfo { number: 18, name: "Job", abbreviation: "Job", aliases: &["job"] },
    BookInfo { number: 19, name: "Psaumes", abbreviation: "Ps", aliases: &["psaumes", "psaume"] },
    BookInfo { number: 20, name: "Proverbes", abbreviation: "Prov", aliases: &["proverbes"] },
    BookInfo { number: 21, name: "Ecclesiaste", abbreviation: "Eccl", aliases: &["ecclesiaste", "ecclésiaste"] },
    BookInfo { number: 22, name: "Cantique des Cantiques", abbreviation: "Cant", aliases: &["cantique", "cantique des cantiques"] },
    BookInfo { number: 23, name: "Esaie", abbreviation: "Esa", aliases: &["esaie", "ésaïe", "isaie", "isaïe"] },
    BookInfo { number: 24, name: "Jeremie", abbreviation: "Jer", aliases: &["jeremie", "jérémie"] },
    BookInfo { number: 25, name: "Lamentations", abbreviation: "Lam", aliases: &["lamentations"] },
    BookInfo { number: 26, name: "Ezechiel", abbreviation: "Eze", aliases: &["ezechiel", "ézéchiel"] },
    BookInfo { number: 27, name: "Daniel", abbreviation: "Dan", aliases: &["daniel"] },
    BookInfo { number: 28, name: "Osee", abbreviation: "Os", aliases: &["osee", "osée"] },
    BookInfo { number: 29, name: "Joel", abbreviation: "Joel", aliases: &["joel", "joël"] },
    BookInfo { number: 30, name: "Amos", abbreviation: "Am", aliases: &["amos"] },
    BookInfo { number: 31, name: "Abdias", abbreviation: "Abd", aliases: &["abdias"] },
    BookInfo { number: 32, name: "Jonas", abbreviation: "Jon", aliases: &["jonas"] },
    BookInfo { number: 33, name: "Michee", abbreviation: "Mich", aliases: &["michee", "michée"] },
    BookInfo { number: 34, name: "Nahum", abbreviation: "Nah", aliases: &["nahum"] },
    BookInfo { number: 35, name: "Habacuc", abbreviation: "Hab", aliases: &["habacuc", "habakuk"] },
    BookInfo { number: 36, name: "Sophonie", abbreviation: "Soph", aliases: &["sophonie"] },
    BookInfo { number: 37, name: "Aggee", abbreviation: "Agg", aliases: &["aggee", "aggée"] },
    BookInfo { number: 38, name: "Zacharie", abbreviation: "Zach", aliases: &["zacharie"] },
    BookInfo { number: 39, name: "Malachie", abbreviation: "Mal", aliases: &["malachie"] },
    BookInfo { number: 40, name: "Matthieu", abbreviation: "Matt", aliases: &["matthieu"] },
    BookInfo { number: 41, name: "Marc", abbreviation: "Marc", aliases: &["marc"] },
    BookInfo { number: 42, name: "Luc", abbreviation: "Luc", aliases: &["luc"] },
    BookInfo { number: 43, name: "Jean", abbreviation: "Jean", aliases: &["jean"] },
    BookInfo { number: 44, name: "Actes", abbreviation: "Actes", aliases: &["actes", "actes des apotres", "actes des apôtres"] },
    BookInfo { number: 45, name: "Romains", abbreviation: "Rom", aliases: &["romains"] },
    BookInfo { number: 46, name: "1 Corinthiens", abbreviation: "1 Cor", aliases: &["1 corinthiens", "premier corinthiens"] },
    BookInfo { number: 47, name: "2 Corinthiens", abbreviation: "2 Cor", aliases: &["2 corinthiens", "deuxieme corinthiens", "deuxième corinthiens"] },
    BookInfo { number: 48, name: "Galates", abbreviation: "Gal", aliases: &["galates"] },
    BookInfo { number: 49, name: "Ephesiens", abbreviation: "Eph", aliases: &["ephesiens", "éphésiens"] },
    BookInfo { number: 50, name: "Philippiens", abbreviation: "Phil", aliases: &["philippiens"] },
    BookInfo { number: 51, name: "Colossiens", abbreviation: "Col", aliases: &["colossiens"] },
    BookInfo { number: 52, name: "1 Thessaloniciens", abbreviation: "1 Th", aliases: &["1 thessaloniciens", "premier thessaloniciens"] },
    BookInfo { number: 53, name: "2 Thessaloniciens", abbreviation: "2 Th", aliases: &["2 thessaloniciens", "deuxieme thessaloniciens", "deuxième thessaloniciens"] },
    BookInfo { number: 54, name: "1 Timothee", abbreviation: "1 Tim", aliases: &["1 timothee", "1 timothée", "premier timothee", "premier timothée"] },
    BookInfo { number: 55, name: "2 Timothee", abbreviation: "2 Tim", aliases: &["2 timothee", "2 timothée", "deuxieme timothee", "deuxième timothée"] },
    BookInfo { number: 56, name: "Tite", abbreviation: "Tite", aliases: &["tite"] },
    BookInfo { number: 57, name: "Philemon", abbreviation: "Phlm", aliases: &["philemon", "philémon"] },
    BookInfo { number: 58, name: "Hebreux", abbreviation: "Heb", aliases: &["hebreux", "hébreux"] },
    BookInfo { number: 59, name: "Jacques", abbreviation: "Jacq", aliases: &["jacques"] },
    BookInfo { number: 60, name: "1 Pierre", abbreviation: "1 Pi", aliases: &["1 pierre", "premier pierre"] },
    BookInfo { number: 61, name: "2 Pierre", abbreviation: "2 Pi", aliases: &["2 pierre", "deuxieme pierre", "deuxième pierre"] },
    BookInfo { number: 62, name: "1 Jean", abbreviation: "1 Jean", aliases: &["1 jean", "premier jean"] },
    BookInfo { number: 63, name: "2 Jean", abbreviation: "2 Jean", aliases: &["2 jean", "deuxieme jean", "deuxième jean"] },
    BookInfo { number: 64, name: "3 Jean", abbreviation: "3 Jean", aliases: &["3 jean", "troisieme jean", "troisième jean"] },
    BookInfo { number: 65, name: "Jude", abbreviation: "Jude", aliases: &["jude"] },
    BookInfo { number: 66, name: "Apocalypse", abbreviation: "Apoc", aliases: &["apocalypse"] },
];

pub const PT_BOOKS: &[BookInfo] = &[
    BookInfo { number: 1, name: "Genesis", abbreviation: "Gen", aliases: &["genesis", "gênesis"] },
    BookInfo { number: 2, name: "Exodo", abbreviation: "Ex", aliases: &["exodo", "êxodo"] },
    BookInfo { number: 3, name: "Levitico", abbreviation: "Lev", aliases: &["levitico", "levítico"] },
    BookInfo { number: 4, name: "Numeros", abbreviation: "Num", aliases: &["numeros", "números"] },
    BookInfo { number: 5, name: "Deuteronomio", abbreviation: "Deut", aliases: &["deuteronomio", "deuteronômio"] },
    BookInfo { number: 6, name: "Josue", abbreviation: "Jos", aliases: &["josue", "josué"] },
    BookInfo { number: 7, name: "Juizes", abbreviation: "Jz", aliases: &["juizes", "juízes"] },
    BookInfo { number: 8, name: "Rute", abbreviation: "Rt", aliases: &["rute"] },
    BookInfo { number: 9, name: "1 Samuel", abbreviation: "1 Sam", aliases: &["1 samuel", "primeiro samuel"] },
    BookInfo { number: 10, name: "2 Samuel", abbreviation: "2 Sam", aliases: &["2 samuel", "segundo samuel"] },
    BookInfo { number: 11, name: "1 Reis", abbreviation: "1 Reis", aliases: &["1 reis", "primeiro reis"] },
    BookInfo { number: 12, name: "2 Reis", abbreviation: "2 Reis", aliases: &["2 reis", "segundo reis"] },
    BookInfo { number: 13, name: "1 Cronicas", abbreviation: "1 Cr", aliases: &["1 cronicas", "1 crônicas", "primeiro cronicas", "primeiro crônicas"] },
    BookInfo { number: 14, name: "2 Cronicas", abbreviation: "2 Cr", aliases: &["2 cronicas", "2 crônicas", "segundo cronicas", "segundo crônicas"] },
    BookInfo { number: 15, name: "Esdras", abbreviation: "Ed", aliases: &["esdras"] },
    BookInfo { number: 16, name: "Neemias", abbreviation: "Ne", aliases: &["neemias"] },
    BookInfo { number: 17, name: "Ester", abbreviation: "Et", aliases: &["ester"] },
    BookInfo { number: 18, name: "Jo", abbreviation: "Jo", aliases: &["jo", "jó"] },
    BookInfo { number: 19, name: "Salmos", abbreviation: "Sl", aliases: &["salmos", "salmo"] },
    BookInfo { number: 20, name: "Proverbios", abbreviation: "Pv", aliases: &["proverbios", "provérbios"] },
    BookInfo { number: 21, name: "Eclesiastes", abbreviation: "Ec", aliases: &["eclesiastes"] },
    BookInfo { number: 22, name: "Canticos", abbreviation: "Ct", aliases: &["canticos", "cânticos", "cantares", "cantico dos canticos", "cântico dos cânticos"] },
    BookInfo { number: 23, name: "Isaias", abbreviation: "Is", aliases: &["isaias"] },
    BookInfo { number: 24, name: "Jeremias", abbreviation: "Jr", aliases: &["jeremias"] },
    BookInfo { number: 25, name: "Lamentacoes", abbreviation: "Lm", aliases: &["lamentacoes", "lamentações"] },
    BookInfo { number: 26, name: "Ezequiel", abbreviation: "Ez", aliases: &["ezequiel"] },
    BookInfo { number: 27, name: "Daniel", abbreviation: "Dn", aliases: &["daniel"] },
    BookInfo { number: 28, name: "Oseias", abbreviation: "Os", aliases: &["oseias"] },
    BookInfo { number: 29, name: "Joel", abbreviation: "Jl", aliases: &["joel"] },
    BookInfo { number: 30, name: "Amos", abbreviation: "Am", aliases: &["amos", "amós"] },
    BookInfo { number: 31, name: "Obadias", abbreviation: "Ob", aliases: &["obadias"] },
    BookInfo { number: 32, name: "Jonas", abbreviation: "Jn", aliases: &["jonas"] },
    BookInfo { number: 33, name: "Miqueias", abbreviation: "Mq", aliases: &["miqueias"] },
    BookInfo { number: 34, name: "Naum", abbreviation: "Na", aliases: &["naum"] },
    BookInfo { number: 35, name: "Habacuque", abbreviation: "Hc", aliases: &["habacuque"] },
    BookInfo { number: 36, name: "Sofonias", abbreviation: "Sf", aliases: &["sofonias"] },
    BookInfo { number: 37, name: "Ageu", abbreviation: "Ag", aliases: &["ageu"] },
    BookInfo { number: 38, name: "Zacarias", abbreviation: "Zc", aliases: &["zacarias"] },
    BookInfo { number: 39, name: "Malaquias", abbreviation: "Ml", aliases: &["malaquias"] },
    BookInfo { number: 40, name: "Mateus", abbreviation: "Mt", aliases: &["mateus"] },
    BookInfo { number: 41, name: "Marcos", abbreviation: "Mc", aliases: &["marcos"] },
    BookInfo { number: 42, name: "Lucas", abbreviation: "Lc", aliases: &["lucas"] },
    BookInfo { number: 43, name: "Joao", abbreviation: "Jo", aliases: &["joao", "joão"] },
    BookInfo { number: 44, name: "Atos", abbreviation: "At", aliases: &["atos", "atos dos apostolos", "atos dos apóstolos"] },
    BookInfo { number: 45, name: "Romanos", abbreviation: "Rm", aliases: &["romanos"] },
    BookInfo { number: 46, name: "1 Corintios", abbreviation: "1 Co", aliases: &["1 corintios", "1 coríntios", "primeiro corintios", "primeiro coríntios"] },
    BookInfo { number: 47, name: "2 Corintios", abbreviation: "2 Co", aliases: &["2 corintios", "2 coríntios", "segundo corintios", "segundo coríntios"] },
    BookInfo { number: 48, name: "Galatas", abbreviation: "Gl", aliases: &["galatas", "gálatas"] },
    BookInfo { number: 49, name: "Efesios", abbreviation: "Ef", aliases: &["efesios", "efésios"] },
    BookInfo { number: 50, name: "Filipenses", abbreviation: "Fp", aliases: &["filipenses"] },
    BookInfo { number: 51, name: "Colossenses", abbreviation: "Cl", aliases: &["colossenses"] },
    BookInfo { number: 52, name: "1 Tessalonicenses", abbreviation: "1 Ts", aliases: &["1 tessalonicenses", "primeiro tessalonicenses"] },
    BookInfo { number: 53, name: "2 Tessalonicenses", abbreviation: "2 Ts", aliases: &["2 tessalonicenses", "segundo tessalonicenses"] },
    BookInfo { number: 54, name: "1 Timoteo", abbreviation: "1 Tm", aliases: &["1 timoteo", "1 timóteo", "primeiro timoteo", "primeiro timóteo"] },
    BookInfo { number: 55, name: "2 Timoteo", abbreviation: "2 Tm", aliases: &["2 timoteo", "2 timóteo", "segundo timoteo", "segundo timóteo"] },
    BookInfo { number: 56, name: "Tito", abbreviation: "Tt", aliases: &["tito"] },
    BookInfo { number: 57, name: "Filemom", abbreviation: "Fm", aliases: &["filemom"] },
    BookInfo { number: 58, name: "Hebreus", abbreviation: "Hb", aliases: &["hebreus"] },
    BookInfo { number: 59, name: "Tiago", abbreviation: "Tg", aliases: &["tiago"] },
    BookInfo { number: 60, name: "1 Pedro", abbreviation: "1 Pe", aliases: &["1 pedro", "primeiro pedro"] },
    BookInfo { number: 61, name: "2 Pedro", abbreviation: "2 Pe", aliases: &["2 pedro", "segundo pedro"] },
    BookInfo { number: 62, name: "1 Joao", abbreviation: "1 Jo", aliases: &["1 joao", "1 joão", "primeiro joao", "primeiro joão"] },
    BookInfo { number: 63, name: "2 Joao", abbreviation: "2 Jo", aliases: &["2 joao", "2 joão", "segundo joao", "segundo joão"] },
    BookInfo { number: 64, name: "3 Joao", abbreviation: "3 Jo", aliases: &["3 joao", "3 joão", "terceiro joao", "terceiro joão"] },
    BookInfo { number: 65, name: "Judas", abbreviation: "Jd", aliases: &["judas"] },
    BookInfo { number: 66, name: "Apocalipse", abbreviation: "Ap", aliases: &["apocalipse"] },
];
